# _config_dev.yml - Dev environment configs and overrides

# Site Variables
webmentionTestUrl: true

# Error Checking & Debugging
# liquid:
#     error_mode: warn
#     strict_filters: true
#     strict_variables: true

# strict_front_matter: true

#Get Webmentions using Jekyll-Get
jekyll_get:
  - data: webmention
    json: '_data/sample.yml'
    cache: false
