# _config_dev.yml - Dev environment configs and overrides

# Site Variables
webmentionTestUrl: true

# Error Checking & Debugging
# liquid:
#     error_mode: warn
#     strict_filters: true
#     strict_variables: true

# strict_front_matter: true
