[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Cache-Control = "max-age=0, must-revalidate, public"
        Content-Encoding = "gzip"
