[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Cache-Control = "public, max-age=31536000, immutable"
        maxAgeTarget = "300"
        maxAgeResource = "1576800"
